name = "SStructTT"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SStructTT"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
maxHeartbeats = 0

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.19.0"

[[lean_lib]]
name = "SStructTT"
